### ISSUE TITLE
Run pre-processors after code extraction, not before

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#147]
Would allow them to modify code blocks for the documentation output without impacting code output (and thus reverse mode). They would then, however, merely be post-processors.

Needs discussion...

**Comment by adamreichold** [comment]
As this is on the weekend, I would dare to say that modifying the code output via a hidden pre-processor is even more hideous than macro arguments were...

Or put more earnestly, do you have a use case the requires pre-processing the compiled code instead of the documentation output? If not, opting for the post-processor option would still allow readability-enhancing functionality without further obfuscating the compiled code. It would seem to also significantly reduce complexity as e.g. concerns regarding invertability of the pre-processor transformation vanish and with it the problems of properly detecting and explaining a possible failure of the reverse mode to the user. Otherwise, you would probably need to require pre-processors to implement their own reverse mode. 

Personally, I think that reverse mode is much more important than pre/post-processors and hence would optimize for that feature being solid on the expense of even more flexibility as Yarner is already quite flexible and hence complex as-is.

**Comment by adamreichold** [comment]
This may be a bit too meta, but I think it could useful to write this down somewhere: My preferences with respect to this issue are guided by seeing literate programming as a technical means so that a computer program can be compiled as usual while being presented according to the conventions of other documents more traditionally aimed at human readers. But it is the software design itself that is targeted at human consumption (as it should always be), not its manifestation as a literate program.

On the other of end of the spectrum, I rather see *artistic programming* - aptly coined in https://openaccess.city.ac.uk/id/eprint/20081/ - where the code blocks of the document rather form a sort of raw material that still needs to be composed into a working computer program via macros or similar mechanisms. Personally, I fear that this additional disconnect between presentation and program structure partially defeats the original purpose to improve the readability of computer programs as one is not actually reading the final program.

(Of course, all abstractions have a similar effect, e.g. code reuse in libraries, high-level languages instead of machine code etc. But those abstraction have defined (if leaky) semantics whereas macros are pure syntax which is why I always recommend to prefer the means of abstraction provided by the programming language itself.)

**Comment by mlange-42** [comment]
> As this is on the weekend, I would dare to say that modifying the code output via a hidden pre-processor is even more hideous than macro arguments were...

This is exactly what I had in mind. Not sure if you misunderstood my "Would allow them to modify code blocks" (followed by "without impacting code output"). But probably, you simply give me more reasons to turn them into "post-processors" 😉

**Comment by adamreichold** [comment]
> But probably, you simply give me more reasons to turn them into "post-processors"

Yes, I am very much trying to argue the case of post-processors.

**Comment by mlange-42** [comment]
Yes, I think I will do that. I also see no use case where modifying code before extraction makes sense. A use case for modifying them afterwards, however, could be to revive comment extraction.

It is a minor point, but how to call them in the config file? `postprocessor.xyz`, or maybe shorter `plugin.xyz`...

**Comment by adamreichold** [comment]
> It is a minor point, but how to call them in the config file? postprocessor.xyz, or maybe shorter plugin.xyz...

Maybe side step the issue and just use "processor". But "plugin" certainly works as well.

**Comment by mlange-42** [comment]
Implemented in #148
